#!/usr/bin/env python3
"""
Build script for Tandroid's documentation site.

WHY THIS EXISTS
----------------
Previously this repository committed *two* files per guide page:
    docs/guide/<slug>.md    <- source of truth, hand-edited
    docs/guide/<slug>.html  <- a pre-rendered copy for GitHub Pages

Keeping both in sync by hand is exactly the kind of duplication that
causes docs to drift (edit the .md, forget the .html, and the live
site silently goes stale).

Now there is exactly ONE file per guide: docs/guide/<slug>.md.
This script renders the full static site (including the sidebar,
theme toggle, pagination, etc. that used to be hand-copied into every
.html file) into a `site/` output directory. That output directory is
a *build artifact* — it is not committed to git, it is generated by
the "Deploy Docs" GitHub Actions workflow on every push and published
to GitHub Pages.

USAGE
-----
    python3 docs/build.py [--out site]

Requires: markdown, pygments, pyyaml (see docs/requirements.txt)
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import markdown
import yaml

# Rewrites relative links between guide pages that are written the
# GitHub-friendly way in the .md sources (so the docs are still
# fully readable/clickable when browsed directly on GitHub) into the
# .html links the built site actually needs, e.g.:
#   href="configuration.md"       -> href="configuration.html"
#   href="configuration.md#foo"   -> href="configuration.html#foo"
_MD_LINK_RE = re.compile(r'href="([a-zA-Z0-9_-]+)\.md(#[^"]*)?"')

DOCS_DIR = Path(__file__).resolve().parent
GUIDE_DIR = DOCS_DIR / "guide"
ASSETS_DIR = DOCS_DIR / "assets"
NAV_FILE = DOCS_DIR / "nav.yaml"

SITE_NAME = "Tandroid"
SITE_TAGLINE = "Tandroid Docs"


def load_nav() -> dict:
    with open(NAV_FILE, encoding="utf-8") as f:
        return yaml.safe_load(f)


def flat_pages(nav: dict) -> list[dict]:
    """Home page + every group item, in the exact order used for
    the sidebar and for prev/next pagination."""
    pages = [{"slug": nav["home"]["slug"], "title": nav["home"]["title"], "group": None}]
    for group in nav["groups"]:
        for item in group["items"]:
            pages.append({"slug": item["slug"], "title": item["title"], "group": group["name"]})
    return pages


def render_markdown(md_text: str) -> str:
    md = markdown.Markdown(
        extensions=["extra", "codehilite", "toc", "sane_lists"],
        extension_configs={
            "codehilite": {"guess_lang": False, "startinline": True},
            "toc": {"permalink": False},
        },
    )
    html = md.convert(md_text)
    return _MD_LINK_RE.sub(r'href="\1.html\2"', html)


def build_sidebar(nav: dict, current_slug: str) -> str:
    home = nav["home"]
    home_active = " active" if current_slug == home["slug"] else ""
    parts = [f'<a class="side-link{home_active}" href="index.html">Home</a>']

    for gi, group in enumerate(nav["groups"]):
        group_id = f"group-{gi}"
        has_active = any(item["slug"] == current_slug for item in group["items"])
        collapsed_class = "" if has_active else " collapsed"
        items_html = []
        for item in group["items"]:
            active = " active" if item["slug"] == current_slug else ""
            items_html.append(
                f'<a class="side-link{active}" href="{item["slug"]}.html">{item["title"]}</a>'
            )
        parts.append(
            f'<div class="side-group{collapsed_class}" data-group="{group_id}">\n'
            f'<button type="button" class="side-group-header" data-group-toggle="{group_id}">'
            f'<span>{group["name"]}</span><span class="chevron">&#9660;</span></button>\n'
            f'<div class="side-group-items">\n{"".join(items_html)}\n</div></div>'
        )
    return "\n".join(parts)


PAGE_TEMPLATE = """<!doctype html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} — {tagline}</title>
<link rel="stylesheet" href="../assets/style.css">
<link rel="stylesheet" href="../assets/docs.css">
<link rel="stylesheet" href="../assets/pygments.css">
</head>
<body>
<a class="skip" href="#content">Skip to content</a>
<button class="btn theme" data-theme-toggle aria-label="Toggle theme">Theme</button>
<button class="btn sidebar-toggle" data-sidebar-toggle aria-label="Toggle sidebar">Menu</button>
<div class="docs-shell">
  <aside class="docs-sidebar" data-sidebar>
    <div class="sidebar-brand">
      <a href="../index.html" class="logo">
        <svg class="logo-mark" viewBox="0 0 48 48" fill="none" width="26" height="26"><path d="M24 6l14 8v20l-14 8-14-8V14l14-8Z" stroke="currentColor" stroke-width="2.5"/></svg>
        <span>{site_name}</span>
      </a>
    </div>
    <nav class="sidebar-nav">
{sidebar}
</nav>
  </aside>
  <main id="content" class="docs-content">
    <div class="docs-article">
      {content}
      <div class="docs-pagination">
        {prev_link}{next_link}
      </div>
    </div>
  </main>
</div>
<script>
(function(){{
  const r=document.documentElement,t=document.querySelector('[data-theme-toggle]');
  let d=localStorage.getItem('aicrion-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
  r.setAttribute('data-theme',d);
  t&&t.addEventListener('click',()=>{{
    d=d==='dark'?'light':'dark';
    r.setAttribute('data-theme',d);
    localStorage.setItem('aicrion-theme',d);
  }});

  const s=document.querySelector('[data-sidebar]'),st=document.querySelector('[data-sidebar-toggle]');
  st&&st.addEventListener('click',()=>s.classList.toggle('open'));

  const STORAGE_KEY='aicrion-sidebar-groups';
  let groupState={{}};
  try {{ groupState=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{{}}'); }} catch(e) {{}}

  document.querySelectorAll('[data-group-toggle]').forEach(function(btn){{
    const id=btn.getAttribute('data-group-toggle');
    const group=btn.closest('.side-group');
    if (Object.prototype.hasOwnProperty.call(groupState, id)) {{
      group.classList.toggle('collapsed', groupState[id]===true);
    }}
    btn.addEventListener('click',function(){{
      const collapsed=group.classList.toggle('collapsed');
      groupState[id]=collapsed;
      localStorage.setItem(STORAGE_KEY, JSON.stringify(groupState));
    }});
  }});
}})();
</script>
</body>
</html>
"""


def build(out_dir: Path) -> None:
    nav = load_nav()
    pages = flat_pages(nav)

    guide_out = out_dir / "guide"
    guide_out.mkdir(parents=True, exist_ok=True)

    for i, page in enumerate(pages):
        slug = page["slug"]
        md_path = GUIDE_DIR / f"{slug}.md"
        if not md_path.exists():
            print(f"WARNING: {md_path} listed in nav.yaml but missing, skipping", file=sys.stderr)
            continue

        content_html = render_markdown(md_path.read_text(encoding="utf-8"))
        sidebar_html = build_sidebar(nav, slug)

        prev_link = f'<a href="{pages[i-1]["slug"]}.html">&larr; {pages[i-1]["title"]}</a>' if i > 0 else "<span></span>"
        next_link = f'<a href="{pages[i+1]["slug"]}.html">{pages[i+1]["title"]} &rarr;</a>' if i < len(pages) - 1 else "<span></span>"

        html = PAGE_TEMPLATE.format(
            title=page["title"],
            tagline=SITE_TAGLINE,
            site_name=SITE_NAME,
            sidebar=sidebar_html,
            content=content_html,
            prev_link=prev_link,
            next_link=next_link,
        )
        (guide_out / f"{slug}.html").write_text(html, encoding="utf-8")
        print(f"built guide/{slug}.html")

    # Landing page and static assets are already single-file / non-duplicated,
    # so they are copied through as-is.
    shutil.copy2(DOCS_DIR / "index.html", out_dir / "index.html")
    shutil.copytree(ASSETS_DIR, out_dir / "assets", dirs_exist_ok=True)
    print(f"\nDocs site built into: {out_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DOCS_DIR.parent / "site"), help="output directory")
    args = parser.parse_args()

    out_dir = Path(args.out).resolve()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    build(out_dir)


if __name__ == "__main__":
    main()
